---
#-----------------------------------
# Ansible variables for all hosts
#-----------------------------------
ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_ssh_ed25519 #~/.ssh/id_ed25519
# ansible_ssh_pass: Password123!

splunk_package_version: 9.3.3  # Default Splunk version to install or update to
build_id: 75595d8f83ef #51ccf43db5bd  # Default build ID for Splunk package


# wget -O splunk-9.4.1-e3bdab203ac8-linux-amd64.tgz "https://download.splunk.com/products/splunk/releases/9.4.1/linux/splunk-9.4.1-e3bdab203ac8-linux-amd64.tgz"

#-----------------------------------
# Github variables for all hosts
#-----------------------------------
git_server: ssh://git@github.com:Zephynyah/splunk-ansible-apps.git
git_key: ~/.ssh/ansible
# git_project: SOMEPROJECT
git_branch: main

#-----------------------------------
# Splunk variables for all hosts 
#-----------------------------------
# Splunk server URI for license master
# This is the server that will be used to manage licenses
# This should be the same as the splunk_uri_lm variable
# If you are using a different server for the license master, change this variable accordingly
splunk_uri_lm: https://rh8-ds-1:8089

# Splunk server URI for deployment server
# This is the server that will be used to deploy apps and configurations to other Splunk servers
# This should be the same as the splunk_uri_lm variable
# If you are using a different server for the deployment server, change this variable accordingly
splunk_uri_ds: rh8-ds-1:8089

# Splunk admin password
# This is the password used to authenticate to the Splunk server
# This password should be kept secret and not shared with anyone
splunk_admin_password: 'Nosw3R&dAcukoqaS*SW='

# Splunk server URI for search head
# This is the server that will be used to search data
# This should be the same as the splunk_uri_lm variable
# If you are using a different server for the search head, change this variable accordingly
splunk_uri_sh: https://rh8-sh-1:8089

#-----------------------
# Splunk CA variables
#------------------------
# Splunk CA Root directory
# This is where the root CA certificate and private key will be stored
# This directory should be secured and not accessible to unauthorized users
# The default is /etc/splunk. You can change this to a different directory if needed
splunkca_directory: "/etc/splunk"

# Splunk CA root passphrase
# This is the passphrase used to encrypt the root CA private key
# This passphrase should be kept secret and not shared with anyone
splunkca_passphrase: "b@2&T5GA=T66uNLn?4ic"
