---
- name: Create inputs.conf for Splunk
  ansible.builtin.template:
    src: "indexer/inputs.conf.j2"
    dest: "{{ splunk_home }}/etc/system/local/inputs.conf"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: "0644"
  become: true
  when: "'indexer' in group_names"
  notify: restart indexer

- block:
    - name: Ensure Splunk is running on the search head
      ansible.builtin.command: "{{ splunk_home }}/bin/splunk start"
      become: true
      when: "'search' in group_names"

    - name: Check remote Splunk instance is running
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:{{ splunkd_port }}"
        method: GET
        validate_certs: false
        use_proxy: no
      register: task_response
      until:
        - task_response.status == 200
      retries: 3
      delay: 30
      ignore_errors: true
      when: "'search' in group_names"

    - name: Get current search peers
      ansible.builtin.command: "{{ splunk_home }}/bin/splunk list search-server -auth {{ splunk_admin_username }}:{{ splunk_admin_password }}"
      register: current_search_peers
      become: true
      when: "'search' in group_names"

    - name: Add indexers as search peers to the search head
      ansible.builtin.command: >
        {{ splunk_home }}/bin/splunk add search-server
        https://{{ item }}:{{ splunkd_port }}
        -auth {{ splunk_admin_username }}:{{ splunk_admin_password }}
        -remoteUsername {{ splunk_admin_username }}
        -remotePassword {{ splunk_admin_password }}
      with_items: "{{ groups['indexer'] }}"
      when:
        - "'search' in group_names"
        - "'https://{}:{}'.format(item, splunkd_port) not in current_search_peers.stdout"
      become: true
      register: add_search_peer_result
      failed_when: add_search_peer_result.rc not in [0, 24]
      changed_when: add_search_peer_result.rc == 0
      no_log: true

    - name: Restart Splunk on the search head to apply configuration
      ansible.builtin.service:
        name: "{{ systemd_unit_full }}"
        state: restarted
      become: true
      when: add_search_peer_result is changed
    
  when:
    - groups['indexer'] | length > 0
    - splunk_admin_username is defined
    - splunk_admin_password is defined

