---
# defaults file for splunkca

# if true, the CA will be created even if it already exists
splunkca_force_create_ownca: false

# if true, the certs will be created even if they already exist
splunkca_force_create_certs: false 

# The directory where the CA will be created
# this is the directory that will be used to store the CA and server files
splunkca_directory: "/etc/splunk"

# where to generate the ownca certs
splunkca_ownca_dir: "{{ splunkca_directory }}/ca"

# Where to generate the server certs
# This is the directory that will be used to store the server certs, private keys and CSR files
splunkca_certs_dir: "{{ splunkca_directory }}/certs"

# The password for the private key`
# this is the password that will be used to encrypt the private key
splunkca_passphrase: ""

# The certificate authority (CA) certificate
# this is the certificate that will be used to sign the server certificates
splunkca_certificate: 'ownca.pem'

# The private key for the CA certificate
# this is the private key that will be used to sign the server certificates
splunkca_privatekey: 'ownca.key'

# The private key for the CA certificate
# this is the private key that will be used to sign the server certificates
splunkca_csr: 'ownca.csr'

# The certificate authority (CA) certificate path
# this is the path of the server certificate
splunkca_certificate_path: "{{ splunkca_ownca_dir }}/{{ splunkca_certificate }}"

# The private key for the CA certificate path
# this is the path of the server private key
splunkca_privatekey_path: "{{ splunkca_ownca_dir }}/{{ splunkca_privatekey }}"

# The private key for the CA certificate path
# this is the path of the server private key
splunkca_csr_path: "{{ splunkca_ownca_dir }}/{{ splunkca_csr }}"

# Create certificate authority (CA) CSR certificate
# If true, a CSR certificate will be generated for the CA
splunkca_generate_ownca_csr: false

# Anchors directory for the CA certs
# this is where the CA certificate will be copied on the server
# this is the directory that will be used by the OS to trust the certs
splunkca_server_anchors_dir: /etc/pki/ca-trust/source/anchors/

# The CSR certificates information
# Used by higher Certificate Authority to create signed the certificate. 
# If true, a CSR certificate will be generated. 
splunkca_generate_server_csr: false 

# this is the information that will be used to generate the CSR
splunkca_country: US # 2 letter country code
splunkca_state: Connecticut # state or province name
splunkca_locality: East Hartford # city or locality name
splunkca_organization: "Collateral Splunk CA" # organization name
splunkca_organizationalunit: "Cyber Security" # organizational unit name
splunkca_email: "ca-admin@mail.com" # email address