---
splunk_uri_lm: https://rh8-ds-1:8089
ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
git_server: ssh://git@github.com:Zephynyah/splunk-ansible-apps.git
git_key: ~/.ssh/ansible
git_project: SOMEPROJECT
#--------------------Secret----------------------

#--------------------Secret----------------------
