---
splunk_uri_lm: https://rh8-ds-1:8089
ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
git_server: ssh://git@github.com:Zephynyah/splunk-ansible-apps.git
git_key: ~/.ssh/ansible
git_project: SOMEPROJECT
splunk_admin_password: 'Nosw3R&dAcukoqaS*SW='
clientName: "{{ ansible_hostname }}"  # Default client name
splunk_uri_ds: rh8-ds-1:8089 # e.g. mydeploymentserver.mydomain.com:8089 ; Note that you must also configure the clientName var under either group_vars or host_vars for deploymentclient.conf to be configured
