---
# defaults file for splunkca
# ca_force_create & ca_force_certify_nodes are designed to prevent overiding of existing certificates !
splunkca_directory: "{{ playbook_dir | dirname }}/rootCA"

splunkca_passphrase: ""

splunkca_certificate: 'ownca-certificate.pem'

splunkca_privatekey: 'ownca-certificate.key'

splunkca_certificate_path: "{{ splunkca_directory }}/{{ splunkca_certificate }}"

splunkca_privatekey_path: "{{ splunkca_directory }}/{{ splunkca_privatekey }}"


# splunkca_ssl_certs_dir: "{{ pki_cert_dir | d('/etc/ssl/certs') }}"
# splunkca_ssl_key_dir: "{{ pki_key_dir | d('/etc/ssl/private') }}"

# # how long should remain before we generate a new CA cert ?
# splunkca_cert_expiration_panic_threshold: 604800 # 1 week

# # where to generate the certs
# splunkca_certs_dir: /usr/share/splunk-ca-cert

# Anchors directory for the CA certs
# this is where the certs will be copied to
# this is the directory that will be used by the OS to trust the certs
splunkca_server_anchors_dir: /etc/pki/ca-trust/source/anchors/

# # where to copy the produces files to
# splunkca_distribution_certs_dir: "{{ splunkca_root_directory}}/distribution_certs"

splunkca_country: USA
splunkca_state: Connecticut
splunkca_locality: East Hartford
splunkca_organization: "Splunk CA"
splunkca_domain: "{{ domain.local }}"
splunkca_organizationalunit: IT
splunkca_commonname: "{{ ansible_hostname }}"
splunkca_email: "ca-admin@{{ domain.local }}"