---
# - name: Create a directory if it does not exist
#   ansible.builtin.file:
#     path: "{{ controller_packages_dir | default(lookup('env', 'PWD')) }}"
#     state: directory
#     mode: '0755'
#   delegate_to: localhost
#   run_once: true


- name: Configure SSL for Splunk Instances
  block:
    - name: Ensure the SSL certificate directory exists
      ansible.builtin.file:
        path: "{{ splunk_home }}/etc/auth/{{ ssl_cert_dir }}"
        state: directory
        owner: "{{ splunk_nix_user }}"
        group: "{{ splunk_nix_group }}"
        mode: '0755'

    - name: Update Splunk configuration for SSL
      ansible.builtin.lineinfile:
        path: "{{ splunk_home }}/etc/system/local/server.conf"
        create: true
        owner: "{{ splunk_nix_user }}"
        group: "{{ splunk_nix_group }}"
        mode: '0644'
        line: "{{ item }}"
      with_items:
        - "[sslConfig]"
        - "enableSplunkdSSL = true"
        - "serverCert = etc/auth/{{ ssl_cert_dir }}/{{ ssl_cert_name }}"
        - "sslPassword = {{ ssl_password }}"
        - "privKeyPath = etc/auth/{{ ssl_cert_dir }}/{{ ssl_key_name }}"

    - name: Restart Splunk to apply SSL configuration
      ansible.builtin.service:
        name: "{{ systemd_unit_full }}"
        state: restarted
      become: true
  when:
    - ssl_cert_dir is defined
    - ssl_cert_name is defined
    - ssl_key_name is defined
    - ssl_password is defined