---
# handlers file for splunkca

- name: Restart Splunk to apply SSL configuration
  ansible.builtin.service:
    name: "{{ systemd_unit_full }}"
    state: restarted
  become: true
  listen: Restart Splunk
