---
# vars file for splunk
global_bashrc: /etc/bashrc
chk_config_cmd: chkconfig --add disable-thp
linux_packages:
  - nload
  - iotop
  - iftop
  - sysstat
  - telnet
  - tcpdump
  - htop
  - atop
  - lsof
  - policycoreutils-python-utils
  - policycoreutils
  - setroubleshoot
  - nethogs
  - gdb
  - bind-utils
firewall_service: firewalld
logrotate_file: /etc/logrotate.d/syslog

# Automatically determine desired splunk version string
splunk_file: "{{ splunk_package_url | regex_search('(splunk(?:forwarder)?\\-\\d+[^/]*\\.tgz)') }}"
splunk_v: "{{ splunk_package_url | regex_search('(\\d+\\.\\d+\\.\\d+(?:\\.\\d+)?)') }}"
splunk_build: "{{ splunk_package_url | regex_search('\\d+\\.\\d+\\.\\d+(?:\\.\\d+)?\\-([^-]+)', '\\1') | first }}"
# Create desired splunk version string (to compare with the output from the splunk version command for upgrades)
splunk_version: "{{ splunk_product }} {{ splunk_v }} (build {{ splunk_build }})"
splunk_auth: "{{ splunk_admin_username }}:{{ splunk_admin_password }}"
