---
# Example playbook to upgrade forwarders to point to a new deployment server

- name: Point Forwarders to New Deployment Server
  hosts:
    - uf
  roles:
    - splunk
  become: true
  serial: 50
  any_errors_fatal: true
  max_fail_percentage: 0
  vars:
    - deployment_task: configure_forwarders.yml
