---
# Playbook to perform either a splunk installation or upgrade via the splunk role
- name: Splunk Installation or Upgrade Playbook
  hosts: all
  serial: 100
  tasks:
    - name: Include Splunk role
      ansible.builtin.include_role:
        name: splunk
      vars:
        deployment_task: check_splunk.yml
