---
# Playbook to perform either a splunk installation or upgrade via the splunk role
- name: Splunk Installation or Upgrade Playbook
  hosts: all
  serial: 10
  tasks:
    - name: Include Splunk role
      ansible.builtin.include_role:
        name: splunk
      vars:
        deployment_task: check_splunk.yml
        splunk_package_version: 9.3.0
        build_id: 51ccf43db5bd
