---
# Example playbook to properly configure SSL for Splunk
# https://docs.splunk.com/Documentation/Splunk/9.4.1/Security/SecureSplunkWebusingasignedcertificate


- name: Create Splunk SSL CA
  hosts:
    - full
  roles:
    - splunkca
  become: true
  serial: 50
  any_errors_fatal: true
  max_fail_percentage: 0
  vars:
    - splunkca_task: generate_ownca.yml
