---
# Example playbook to properly add search peers to the search head
# References:
# https://docs.splunk.com/Documentation/Splunk/9.4.0/DistSearch/Configuredistributedsearch
# https://docs.splunk.com/Documentation/Splunk/9.4.0/Forwarding/Enableareceiver

- name: Add search peers to the search head
  hosts:
    - search
  roles:
    - splunk
  become: true
  any_errors_fatal: true
  max_fail_percentage: 0
  vars:
    - deployment_task: configure_search_head.yml

