---
# Example playbook to install/upgrade apps on a Splunk host
# For details on configuring as a deployment server, see 
# $SPLUNK_HOME/etc/system/README/serverclass.conf.spec, serverclass.conf.example or the Admin manual 
# at http://docs.splunk.com/Documentation.

- name: Deploy Splunk Apps
  hosts:
    - all
  roles:
    - splunk
  become: true
  serial: 50
  any_errors_fatal: true
  max_fail_percentage: 0
  vars:
    - deployment_task: configure_apps.yml
