---
- name: git module Playbook
  hosts: localhost
  vars:
    repo: "git@github.com:Zephynyah/splunk-ansible-apps.git"
    dest: "/etc/devops/splunk-ansible-apps"
    sshkey: "~/.ssh/ansible"
  tasks:
    # - name: ensure git pkg installed
    #   ansible.builtin.yum:
    #     name: git
    #     state: present
    #     update_cache: true
    #   become: true

    - name: checkout git repo
      ansible.builtin.git:
        repo: "{{ repo }}"
        dest: "{{ dest }}"
        key_file: "{{ sshkey }}"
        version: "main"
        force: yes
        accept_hostkey: true
      become: true
      # become_user: devops

# - name: Download and deploy Splunk apps from GitHub
#   block:
#     - name: Ensure git is installed
#       ansible.builtin.package:
#         name: git
#         state: present

#     - name: Clone Splunk apps repository
#       ansible.builtin.git:
#         repo: "https://github.com/Zephynyah/splunk-ansible-apps.git"
#         dest: "{{ splunk_home }}/etc/apps/splunk-ansible-apps"
#         version: "main"
#         force: yes
#       become: true
#       become_user: "{{ splunk_nix_user }}"

#     - name: Set permissions for the deployed apps
#       ansible.builtin.file:
#         path: "{{ splunk_home }}/etc/apps/splunk-ansible-apps"
#         state: directory
#         owner: "{{ splunk_nix_user }}"
#         group: "{{ splunk_nix_group }}"
#         recurse: true

#     - name: Restart Splunk to apply new apps
#       ansible.builtin.service:
#         name: splunk
#         state: restarted
#   when:
#     - splunk_home is defined
#     - splunk_nix_user is defined
#     - splunk_nix_group is defined