---
- name: Download and Install Splunk
  hosts: all
  become: yes

  vars:
    splunk_version: "9.4.0"

  tasks:
    - name: Check if Splunk package already exists
      ansible.builtin.stat:
        path: "{{ lookup('env', 'PWD') }}"
      register: splunk_package_status

    - name: Download Splunk package
      ansible.builtin.get_url:
        url: "https://www.splunk.com/page/download_track?file={{ splunk_version }}&ac=default&name=dl&platform=linux&architecture=x86_64&version={{ splunk_version }}&product=splunk&typed=release"
        dest: "/tmp/splunk-{{ splunk_version }}.tgz"
      when: not splunk_package_status.stat.exists
      register: download_status
      delegate_to: localhost
      run_once: true


