---
# For details on configuring as a deployment server, see 
# $SPLUNK_HOME/etc/system/README/serverclass.conf.spec, serverclass.conf.example or the Admin manual 
# at http://docs.splunk.com/Documentation.

- name: Download and Install Splunk
  hosts: deploymentserver
  become: yes

  vars:
    splunk_version: "9.4.0"

  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/ansible/ansible.git'
        dest: /tmp/checkout
        version: v2.18.4
      delegate_to: localhost



