---
# For details on configuring as a deployment server, see 
# $SPLUNK_HOME/etc/system/README/serverclass.conf.spec, serverclass.conf.example or the Admin manual 
# at http://docs.splunk.com/Documentation.

- name: Download and Install Splunk
  hosts: search
  become: yes

  vars:
    splunk_version: "9.4.0"
    splunk_home: "/opt/splunk"
    splunk_nix_user: "splunk"
    splunk_nix_group: "splunk"

  tasks:

  - name: Concatenate indexer IPs into a single string
    set_fact:
      str_indexer_servers: >-
        {% for x in groups['indexer'] %}
        {{ hostvars[x]['ansible_default_ipv4']['address'] }}:9997
        {% if not loop.last %},{% endif %}
        {% endfor %}
    when: groups['indexer'] | length > 0

  - name: Stat the outputs
    ansible.builtin.stat:
      path: "{{ splunk_home }}/etc/system/local/outputs.conf"
    register: outputs_stat


  - name: Template | Configure outputs.conf to turn off indexing and set forwarding
    template:
      src: "{{ playbook_dir}}/../roles/splunk/templates/search/outputs.conf.j2"
      dest: "{{ splunk_home }}/etc/system/local/outputs.conf"
      owner: "{{ splunk_nix_user }}"
      group: "{{ splunk_nix_group }}"
      mode: "0644"
    vars:
      indexer_servers: "{{ str_indexer_servers | replace(' ', '') }}"
    when:
      - outputs_stat.stat.exists == false
      - splunk_home is defined
      - splunk_nix_user is defined
      - splunk_nix_group is defined
    notify:
      - restart splunk
    become: true

  - name: INI | Configure outputs.conf to turn off indexing and set forwarding
    block:
      - name: Configure indexAndForward settings
        community.general.ini_file:
          path: "{{ splunk_home }}/etc/system/local/outputs.conf"
          section: "indexAndForward"
          option: "index"
          value: "false"
          owner: "{{ splunk_nix_user }}"
          group: "{{ splunk_nix_group }}"
          mode: "0644"
        become: true

      - name: Configure tcpout settings
        community.general.ini_file:
          path: "{{ splunk_home }}/etc/system/local/outputs.conf"
          section: "tcpout"
          option: "{{ item.option }}"
          value: "{{ item.value }}"
          owner: "{{ splunk_nix_user }}"
          group: "{{ splunk_nix_group }}"
          mode: "0644"
        with_items:
          - option: "defaultGroup"
            value: "idx_search_peers"
          - option: "forwardedindex.filter.disable"
            value: "true"
          - option: "indexAndForward"
            value: "false"
        become: true

      - name: Configure tcpout:idx_search_peers settings
        community.general.ini_file:
          path: "{{ splunk_home }}/etc/system/local/outputs.conf"
          section: "tcpout:idx_search_peers"
          option: "{{ item.option }}"
          value: "{{ item.value }}"
          owner: "{{ splunk_nix_user }}"
          group: "{{ splunk_nix_group }}"
          mode: "0644"
        with_items:
          - option: "server"
            value: "{{ str_indexer_servers | replace(' ', '') }}"
          - option: "autoLB"
            value: "true"
        become: true
        notify:
          - restart splunk

    when:
      - splunk_home is defined
      - splunk_nix_user is defined
      - splunk_nix_group is defined
      - outputs_stat.stat.exists