---
# vars file for splunk_ca
splunk_home: "/opt/splunk"
splunk_nix_user: "splunk"
splunk_nix_group: "splunk"
systemd_unit_full: "Splunkd"


# ssl_cert_dir: "custom_certs"
# ssl_cert_path: "/path/to/your/certificate.crt"
# ssl_key_path: "/path/to/your/private.key"
# ssl_cert_name: "server.crt"
# ssl_key_name: "server.key"
# ca_root_passphrase: "b@2&T5GA=T66uNLn?4ic"