---
# tasks file for roles/splunk_ca/tasks/generate_ownca.yml
# This file is part of the Ansible role for Splunk CA management.
# It is used to create a self-signed CA certificate and private key.
# This script does not genareat a CSR, but rather uses openssl_csr_pipe to create a CSR in memory.
# The tasks are designed to be idempotent and can be run multiple times without side effects.
# The tasks are executed on the localhost to ensure that the CA certificate and key are generated in a controlled environment.
# The tasks include creating a directory for the CA files, generating a private key and certificate.

- name: Create private key with password protection
  community.crypto.openssl_privatekey:
    path: "{{ splunkca_privatekey_path }}"
    passphrase: "{{ splunkca_passphrase }}"
  delegate_to: localhost
  run_once: true

- name: Pipe | Create certificate signing request (CSR) for CA certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ splunkca_privatekey_path }}"
    privatekey_passphrase: "{{ splunkca_passphrase }}"
    common_name: Ansible CA
    use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: ca_csr
  delegate_to: localhost
  run_once: true
  when: not splunkca_generate_ownca_csr | default(false)

- name: File | Create certificate signing request (CSR) for CA certificate
  community.crypto.openssl_csr:
    path: "{{ splunkca_csr_path }}"
    privatekey_path: "{{ splunkca_privatekey_path }}"
    privatekey_passphrase: "{{ splunkca_passphrase }}"
    common_name: Ansible CA
    use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  delegate_to: localhost
  run_once: true
  when: splunkca_generate_ownca_csr == true

- name: Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ splunkca_certificate_path }}"
    csr_path: "{{ splunkca_csr_path if splunkca_generate_ownca_csr else omit  }}"
    csr_content: "{{ ca_csr.csr if not splunkca_generate_ownca_csr else omit  }}"
    privatekey_path: "{{ splunkca_privatekey_path }}"
    privatekey_passphrase: "{{ splunkca_passphrase }}"
    provider: selfsigned
  delegate_to: localhost
  run_once: true